//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MayIn
    {
        public int ID_MayIn { get; set; }
        public string TenMayIn { get; set; }
        public string MaMayIn { get; set; }
        public string GhiChu { get; set; }
    }
}
