//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NhomTaiKhoan
    {
        public int ID_NhomTaiKhoan { get; set; }
        public string KeyNhomTaiKhoan { get; set; }
        public string TenNhomTaiKhoan { get; set; }
        public string GhiChu { get; set; }
    }
}
