//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_NhomNhanVien
    {
        public int ID_NhomNhanVien { get; set; }
        public string TenNhomNhanVien { get; set; }
        public string KeyNhomNhanVien { get; set; }
        public string GhuChu { get; set; }
        public Nullable<int> SoLuongBanInTrongThang { get; set; }
    }
}
