//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaHan
    {
        public int ID_GiaHan { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
    }
}
