//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HT_ChiTietPhanQuyen
    {
        public int ID_ChiTietPhanQuyen { get; set; }
        public string KeyNhomTaiKhoan { get; set; }
        public string KeyMenu { get; set; }
        public string KeyChucNang { get; set; }
        public Nullable<bool> TrangThai { get; set; }
    }
}
