//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_BanIn
    {
        public int ID_BanIn { get; set; }
        public string TenTaiLieu { get; set; }
        public string MaTaiLieu { get; set; }
        public Nullable<int> ID_NhanVien { get; set; }
        public Nullable<System.DateTime> ThoiGianUpload { get; set; }
        public Nullable<System.DateTime> ThoiGianPrint { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string TrangThaiText { get; set; }
        public Nullable<int> TongSoTrang { get; set; }
        public Nullable<int> TongSoTrangDaIn { get; set; }
        public Nullable<int> JobID { get; set; }
        public string TenMayIn { get; set; }
        public string TenTaiLieuDinhKem { get; set; }
        public string PaperSize { get; set; }
    }
}
