//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMayIn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NV_PrintTam
    {
        public int ID_PrintTam { get; set; }
        public string Bios_MayTinh { get; set; }
        public string TenTaiLieu { get; set; }
        public string TenMayIn { get; set; }
        public string SoMayIn { get; set; }
        public Nullable<int> TongSoTrang { get; set; }
        public Nullable<int> JobID { get; set; }
        public string JobStatus { get; set; }
        public string StatusPrint { get; set; }
        public Nullable<System.DateTime> NgayIn { get; set; }
        public string TrangThaiText { get; set; }
        public string PaperSize { get; set; }
    }
}
